[package]
name = "simple-eyre"
version = "0.2.0"
authors = ["Jane Lusby <jlusby@yaah.dev>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/yaahc/simple-eyre"
homepage = "https://github.com/yaahc/simple-eyre"
documentation = "https://docs.rs/simple-eyre"
keywords = ["error"]
description = """
One of the simplest error reporters one can build ontop of eyre, defining only an error report
"""

[dependencies]
eyre = "0.4.2"
indenter = "0.3.0"
